create table posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text not null,
    link text unique not null,
    description text,
    created timestamp without time zone
);
